In [1]:
import numpy as np

### `np.concatenate(*args)`

You can concatenate as many as you want by passing the arrays.
For 1d array, the elements length doesn't matter.
For 2d+ array, the number of elements must match.

In [2]:
x = np.array([1, 2, 3])
y = np.array([6, 7, 2, 3, 8])
z = np.array([3, 3, 3, 3, 3, 3])
np.concatenate([x, y, z])

array([1, 2, 3, 6, 7, 2, 3, 8, 3, 3, 3, 3, 3, 3])

#### Concatenate 2d array

In [3]:
x = np.array([[1, 3, 5],
              [7, 8, 9]])
y = np.array([[-1, -3, -5],
              [-2, -12, -52]])

In [4]:
np.concatenate([x, y])

array([[  1,   3,   5],
       [  7,   8,   9],
       [ -1,  -3,  -5],
       [ -2, -12, -52]])

This concatenation seems like you **append your array to it**.

This code snippet, instead, specify `axis=1`. 
*Default is `axis=0`*.
It concatenates the first axist.

In [5]:
np.concatenate([x, y], axis=1)

array([[  1,   3,   5,  -1,  -3,  -5],
       [  7,   8,   9,  -2, -12, -52]])

#### Concatenate mixed dimensions array

In [6]:
x = np.array([1, 2, 3])
grid = np.array([[-1, -2, -5],
                 [-4, -5, -1]])

vertically stack the arrays

In [7]:
np.vstack([x, grid])

array([[ 1,  2,  3],
       [-1, -2, -5],
       [-4, -5, -1]])

horizontally stack the arrays

In [8]:
y = np.array([[10], [83]])
np.hstack([grid, y])

array([[-1, -2, -5, 10],
       [-4, -5, -1, 83]])

# concat 2 arrays

[concat two 1d array to a 2d array](https://stackoverflow.com/questions/17710672/create-a-two-dimensional-array-with-two-one-dimensional-arrays#:~:text=If%20you%20wish%20to%20combine,T%20will%20do%20it.)

In [9]:
x_1 = np.absolute(np.random.randn(10) * 10)
x_2 = np.absolute(np.random.randn(10) * 30)

np.vstack((x_1, x_2)).T

array([[ 6.04841274,  9.0846043 ],
       [ 9.29087897, 25.96066855],
       [ 5.455203  , 30.20572841],
       [12.33947964, 26.81771178],
       [ 3.16446376, 31.7349186 ],
       [ 9.43776564, 41.44045359],
       [12.63582039, 40.48339439],
       [ 5.72868549, 31.23078088],
       [19.4883197 ,  9.44455438],
       [11.48502295, 16.28739009]])