In [1]:
import numpy as np

# Reshaping of arrays

> Note that for this to work, the size of the initial array must match the size of the reshaped array. Where possible, the reshape method will use a no-copy view of the initial array

In [2]:
grid = np.arange(1, 10)
grid_reshape = grid.reshape((3, 3))
grid_reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
x = np.array([1, 2, 3])
x = x.reshape((1, 3))
x

array([[1, 2, 3]])

In [4]:
x.shape

(1, 3)

## `reshape(-1, 1)` : from 1 dimension to 2 dimensions

In [9]:
x = np.arange(10)
print(x.shape)
print(x)

(10,)
[0 1 2 3 4 5 6 7 8 9]


In [10]:
x = x.reshape(-1, 1)
print(x.shape)
print(x)

(10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


# `np.newaxis`

Another way to reshape is `np.newaxis`

[stackoverflow](https://stackoverflow.com/questions/29241056/how-do-i-use-np-newaxis)

![numpy newaxis](https://i.stack.imgur.com/zkMBy.png)

In [7]:
x[np.newaxis, :]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]]])

In [ ]:
x[:, np.newaxis]