In [1]:
import numpy as np

# Splitting of arrays

The below splits the array into 3 variables

In [2]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [3]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [5]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### The slice is Not-a-copy - modification takes place

>The value actually changes if you modify

Use `copy()` to create a copy

In [6]:
x = np.array([1, 3, 5])
subX = x[:2]
subX[0] = 99

In [7]:
x

array([99,  3,  5])

For Python list, the slicing subarray does not change!

In [8]:
pythonList = [1, 3, 6]
secondList = pythonList[:1]
secondList[0] = -33
secondList

[-33]

In [9]:
pythonList

[1, 3, 6]